name: AchievementChallenge
version: 1.0.0
main: de.achievementchallenge.AchievementChallengePlugin
api-version: 1.21
author: Der allerechte Intäligäns
description: Alle gegen Astro(voraussichtlich)
depend:
  - ProtocolLib
  - Citizens


commands:
  # Timer-Commands (übernommen aus MobHunt)
  timerstart:
    description: Startet den Timer
    usage: /timerstart
    permission: achievementchallenge.timer.admin

  timerpause:
    description: Pausiert den Timer
    usage: /timerpause
    permission: achievementchallenge.timer.admin

  timerresume:
    description: Setzt den Timer fort
    usage: /timerresume
    permission: achievementchallenge.timer.admin

  timer:
    description: Zeigt den Timer an
    usage: /timer

  timerreset:
    description: Setzt den Timer zurück
    usage: /timerreset
    permission: achievementchallenge.timer.admin

  timertoggle:
    description: Schaltet die ActionBar um
    usage: /timertoggle

  # Challenge-Commands (neu)
  seteinzelkaempfer:
    description: Setzt einen Spieler als Einzelkämpfer
    usage: /seteinzelkaempfer <spieler>
    permission: achievementchallenge.challenge.admin

  showeinzelkaempfer:
    description: Zeigt den aktuellen Einzelkämpfer
    usage: /showeinzelkaempfer
    aliases: [einzelkaempfer]

  challengestatus:
    description: Zeigt den Challenge-Status in einer GUI
    usage: /challengestatus
    aliases: [cstatus]

  resetchallenge:
    description: Setzt die Challenge zurück
    usage: /resetchallenge
    permission: achievementchallenge.challenge.admin

  ch:
    description: Werde ein Dämon mit Troll-Kräften
    usage: /ch

  anonym:
    description: Alle Spieler sehen aus wie der Zielspieler
    usage: /anonym <Spieler> <Minuten>
    permission: achievementchallenge.daemon

  ankuendigung:
    description: Sendet eine rote, fette Nachricht in den Chat
    usage: /ankuendigung <Nachricht>
    permission: achievementchallenge.daemon

  audiotest:
    description: Spielt Horror-Sounds beim Zielspieler
    usage: /audiotest <Spieler>
    permission: achievementchallenge.daemon

  kaffepause:
    description: Kick alle mit einer Ausrede
    usage: /kaffepause
    permission: achievementchallenge.daemon

  lag:
    description: Friert alle Spieler und Entities ein
    usage: /lag
    permission: achievementchallenge.daemon

  befreimich:
    description: Gibt Dämonen ein Befreiungs-Totem
    usage: /befreimich
    permission: achievementchallenge.daemon

  blur:
    description: Macht den Bildschirm eines Spielers verschwommen
    usage: /blur <Spieler> <Sekunden>
    permission: achievementchallenge.daemon

  ko:
    description: Kickt alle geblurete Spieler
    usage: /ko
    permission: achievementchallenge.daemon

  schielen:
    description: Gibt subtile Lag-Effekte
    usage: /schielen <Spieler>
    permission: achievementchallenge.daemon

  immun:
    description: Macht einen Spieler immun gegen Bans
    usage: /immun <Spieler>
    permission: achievementchallenge.daemon

  psychischbedingt:
    description: Fake Damage-Effekte ohne echten Schaden
    usage: /psychischbedingt <Spieler>
    permission: achievementchallenge.daemon

  echo:
    description: Alle Sounds werden mit Verzögerung wiederholt
    usage: /echo [Spieler]
    permission: achievementchallenge.daemon

  upsidedown:
    description: Dreht die Welt für 5 Sekunden auf den Kopf
    usage: /upsidedown <Spieler>
    permission: achievementchallenge.daemon

  schatten:
    description: Spawnt einen Schatten-Doppelgänger (Toggle)
    usage: /schatten <Spieler>
    permission: achievementchallenge.daemon

permissions:
  achievementchallenge.timer.admin:
    description: Erlaubt Timer-Administration
    default: op

  achievementchallenge.challenge.admin:
    description: Erlaubt Challenge-Administration
    default: op

  achievementchallenge.daemon:
    description: Erlaubt Dämon-Commands (automatisch für Dämonen)